security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 
    role_hierarchy:
        ROLE_DOCENTE:     ROLE_USER
        ROLE_ADMIN:       ROLE_USER, ROLE_DOCENTE
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    firewalls:
        dev:
            pattern:    ^/(_profiler|_wdt|css|js)
            security:   false
        main:
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
                provider: fos_userbundle
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            #security: true
            anonymous: ~

            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/docentes, role: ROLE_ADMIN }
        - { path: ^/divisiones, role: ROLE_DOCENTE }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }