generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Legajocategoria
    theme:            default
    fields:
          descripcion: {name: Descripci&oacute;n , params: size=64 }
    list:
          title: Tipos de entrada al legajo pedag&oacute;gico
          display: [ descripcion]
          sort: descripcion
          object_actions:
              _edit: -
              _delete: -
    edit:
          title: Editar &iacute;tems de legajo pedag&oacute;gico
          display: [ descripcion ]
          actions:
              _delete: -
              _save: - 
              _save_and_add: -
              _list: -
                    
